syntax = "proto3";

option java_package = "com.flipfoundry.tutorial.events";
option java_multiple_files = true;

import "google/protobuf/timestamp.proto";

// -----------------------------------------------
// Greeting Events
// -----------------------------------------------

message GreetingEvent {
  string event_id  = 1;
  string name      = 2;
  string message   = 3;
  string locale    = 4;
  google.protobuf.Timestamp occurred_at = 5;
}

// -----------------------------------------------
// Departing Events
// -----------------------------------------------

message DepartingEvent {
  string event_id  = 1;
  string name      = 2;
  string farewell  = 3;
  google.protobuf.Timestamp occurred_at = 4;
}
