# ===============================
# = Spring Doc
# ===============================
springdoc:
  swagger-ui:
    enabled: false

# ===============================
# = Actuator / Health Probes - Production Overrides
# ===============================
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,livenessProbe,readinessProbe

  endpoint:
    health:
      show-details: when-authorized

  health:
    diskSpace:
      enabled: false

# ===============================
# = OpenTelemetry - Enabled for Production
# ===============================
otel:
  sdk:
    disabled: false
  exporter:
    otlp:
      protocol: grpc
      endpoint: http://collector:4317
  traces:
    exporter: otlp
  metrics:
    exporter: otlp
  logs:
    exporter: otlp
  resource:
    attributes:
      'service.name': spring-microservice-template
      'service.version': '0.0.1-SNAPSHOT'
  instrumentation:
    logback-appender:
      enabled: true
    micrometer:
      enabled: true
